# Default noising configuration
# structure follows:
#   Row noise: `form.noise_type`
#   Column-wise parameters: `form.column.noise_type.noise_parameter`

decennial_census:
    omission: 0.0145
    duplication: 0.05
    first_name:
        nickname:
            row_noise_level: 0.01
        fake_names:
            row_noise_level: 0.01
        missing_data:
            row_noise_level: 0.01
        phonetic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        ocr:
            row_noise_level: 0.01
            token_noise_level: 0.1
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
    age:
        missing_data:
            row_noise_level: 0.01
        ocr:
            row_noise_level: 0.01
            token_noise_level: 0.1
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        age_miswriting:
            row_noise_level: 0.01
            age_miswriting: [1, -1]
    zipcode:
        missing_data:
            row_noise_level: 0.01
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        zipcode_miswriting:
            row_noise_level: 0.01
            zipcode_miswriting: [0.04, 0.04, 0.2, 0.36, 0.36]

american_communities_survey:
    omission: 0.0145
    duplication: 0.05
    first_name:
        nickname:
            row_noise_level: 0.01
        fake_names:
            row_noise_level: 0.01
        missing_data:
            row_noise_level: 0.01
        phonetic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        ocr:
            row_noise_level: 0.01
            token_noise_level: 0.1
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
    age:
        missing_data:
            row_noise_level: 0.01
        ocr:
            row_noise_level: 0.01
            token_noise_level: 0.1
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        age_miswriting:
            row_noise_level: 0.01
            age_miswriting: [1, -1]
    zipcode:
        missing_data:
            row_noise_level: 0.01
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        zipcode_miswriting:
            row_noise_level: 0.01
            zipcode_miswriting: [0.04, 0.04, 0.2, 0.36, 0.36]

current_population_survey:
    omission: 0.2905
    duplication: 0.05
    first_name:
        nickname:
            row_noise_level: 0.01
        fake_names:
            row_noise_level: 0.01
        missing_data:
            row_noise_level: 0.01
        phonetic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        ocr:
            row_noise_level: 0.01
            token_noise_level: 0.1
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
    age:
        missing_data:
            row_noise_level: 0.01
        ocr:
            row_noise_level: 0.01
            token_noise_level: 0.1
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        age_miswriting:
            row_noise_level: 0.01
            age_miswriting: [1, -1]
    zipcode:
        missing_data:
            row_noise_level: 0.01
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        zipcode_miswriting:
            row_noise_level: 0.01
            zipcode_miswriting: [0.04, 0.04, 0.2, 0.36, 0.36]

women_infants_and_children:
    omission: 0.0
    duplication: 0.05
    first_name:
        nickname:
            row_noise_level: 0.01
        fake_names:
            row_noise_level: 0.01
        missing_data:
            row_noise_level: 0.01
        phonetic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        ocr:
            row_noise_level: 0.01
            token_noise_level: 0.1
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
    age:
        missing_data:
            row_noise_level: 0.01
        ocr:
            row_noise_level: 0.01
            token_noise_level: 0.1
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        age_miswriting:
            row_noise_level: 0.01
            age_miswriting: [1, -1]
    zipcode:
        missing_data:
            row_noise_level: 0.01
        typographic:
            row_noise_level: 0.01
            token_noise_level: 0.1
        zipcode_miswriting:
            row_noise_level: 0.01
            zipcode_miswriting: [0.04, 0.04, 0.2, 0.36, 0.36]

# TODO: add the rest of observers/forms with RT input
#social_security:
#
#taxes_w2_and_1099:
#
#taxes_1040:
