# -----------------------------------------------------------------------------
#   - invoked on push, pull_request, manual trigger, or schedule
#   - test under all supported versions of python (python_versions.json)
# -----------------------------------------------------------------------------
name: build
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
  
jobs:
  get-python-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get install jq
      - name: Get Python versions
        id: set-matrix
        run: |
          echo "MATRIX_RESULT=$(jq -c . python_versions.json)" >> $GITHUB_ENV
    outputs:
      matrix: ${{ env.MATRIX_RESULT }}
  build:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    uses: 
      ihmeuw/vivarium_build_utils/.github/workflows/build.yml@main
    with:
      dependencies: "layered_config_tree"
      python_version: ${{ matrix.python-version }}
      skip_mypy: true
    secrets:
      notify_email: ${{ secrets.NOTIFY_EMAIL }}
      NOTIFY_PASSWORD: ${{ secrets.NOTIFY_PASSWORD }}
