name: Notify-test

on:
  workflow_dispatch:
  push:
    branches: mic-4384/notify-cron-fail

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo Hello, world! && exit 1
      - name: Send mail
        if: job.status == 'failure'
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.NOTIFY_EMAIL }}
          password: ${{ secrets.NOTIFY_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: albrja@uw.edu
          # from email name
          from: Dr Manhattan